on:
  push:
    branches:
      - master
name: FTP Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync File
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
